### ISSUE TITLE
Update problems

### ISSUE THREAD

**Issue by endovitskayaV** [nicolaspayot/bic#2]
Hi
After you made updates an hour ago, I have a problem with the lib.
'bic' is not found any more,  even if run npm install bic it is not loaded, I get only .travis.yml, LISENCE, package.json and README.MD files in build folder
Could you please fix that?

**Comment by nicolaspayot** [comment]
Hi, sorry for this bad release. It's been deprecated and a new one has been published: v1.1.1.

**Comment by endovitskayaV** [comment]
Cool, it is okay now. Thank you!
